remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Nima Hosseini Dashtbayaz
logo: /assets/img/profile-photo.jpg
description: MSc Computer Science Student at University of Western Ontario
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
